### PR TITLE
Update index.html to add Tonic under Useful Links

### PR DESCRIPTION
**Pull request by daniellevine**
JS fiddle/REPL-like experience for Node.js

### CODE REVIEW

**Comment by ralt** [comment]
hispam

**Comment by benjamingr** [comment]
Why not @ralt ?

**Comment by ralt** [comment]
Is it actually legit? I never heard about OP nor this "Tonic", so I just
assumed this was spam.
Le 9 oct. 2015 08:36, "Benjamin Gruenbaum" <notifications@github.com> a
écrit :

**Comment by daniellevine** [comment]
I'm not a big deal. Tonic is legit, it's from the guys who created Objective-J (port of Objective-C to javascript).

**Pull request closed without merging**
